- name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: electron-build-artifacts
          path: |
            dist/**/*
            # Adjust paths according to your build output location
